--1
ALTER TABLE PROJEKTY ADD (CONSTRAINT PK_PROJEKTY PRIMARY KEY (ID_PROJEKTU), CONSTRAINT UK_PROJEKTY UNIQUE (OPIS_PROJEKTU), CHECK (DATA_ZAKONCZENIA >DATA_ROZPOCZECIA), CHECK(FUNDUSZE >=0)) MODIFY OPIS_PROJEKTU NOT NULL;

--2
INSERT INTO PROJEKTY (OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZE) VALUES ('INDEKSY_BITMAPOWE', TO_DATE('12-04-2015', 'DD-MM-YYYY'),TO_DATE('30-12-2016','DD-MM-YYYY'),40000);

--3
CREATE TABLE PRZYDZIALY (
    ID_PROJEKTU NUMBER(4) CONSTRAINT FK_PRZYDZIALY_01 REFERENCES PROJEKTY(ID_PROJEKTU) NOT NULL,
    NR_PACOWNIKA NUMBER(6) CONSTRAINT FK_PRZYDZIALY_02 REFERENCES PRACOWNICY(ID) NOT NULL, 
    PRZYDZIAL_OD DATE DEFAULT CURRENT_DATE,
    PRZYDZIAL_DO DATE CONSTRAINT CHK_PRZYDZIALY_DATY CHECK(PRZYDZIAL_DO> PRZYDZIAL_OD),
    STAWKA NUMBER(7,2) CONSTRAINT CHK_PRZYDZIALY_STAWKA CHECK(STAWKA > 0),
    ROLA VARCHAR(20) CONSTRAINT CHK_PRZYDZIALY_ROLA CHECK(ROLA IN ('KIERUJĄCY', 'ANALITYK', 'PROGRAMISTA'))
);

--4
INSERT INTO PRZYDZIALY (ID_PROJEKTU, NR_PACOWNIKA, PRZYDZIAL_OD, PRZYDZIAL_DO, STAWKA, ROLA) VALUES
((SELECT ID_PROJEKTU FROM PROJEKTY WHERE NAZWA = 'Indeksy bitmapowe'), 170, TO_DATE('10-04-1999', 'DD-MM-YYYY'), TO_DATE('10-05-1999', 'DD-MM-YYYY'), 1000, 'KIERUJĄCY');

INSERT INTO PRZYDZIALY (ID_PROJEKTU, NR_PACOWNIKA, PRZYDZIAL_OD, PRZYDZIAL_DO, STAWKA, ROLA) VALUES
((SELECT ID_PROJEKTU FROM PROJEKTY WHERE NAZWA = 'Indeksy bitmapowe'), 140, TO_DATE('01-12-2000', 'DD-MM-YYYY'), NULL, 1500, 'ANALITYK');

INSERT INTO PRZYDZIALY (ID_PROJEKTU, NR_PACOWNIKA, PRZYDZIAL_OD, PRZYDZIAL_DO, STAWKA, ROLA) VALUES
((SELECT ID_PROJEKTU FROM PROJEKTY WHERE NAZWA = 'Sieci kręgosłupowe'), 140, TO_DATE('14-09-2015', 'DD-MM-YYYY'), NULL, 2500, 'KIERUJĄCY');

--5
ALTER TABLE PRZYDZIALY ADD GODZINY NUMBER(4p) CHECK(GODZINY <=9999)) MODIFY (GODZINY NOT NULL);

--6
ALTER TABLE PRZYDZIALY ADD GODZINY NUMBER(4);
CREATE SEQUENCE GODZINKI START WITH 10 INCREMENT BY 10;
UPDATE PRZYDZIALY SET GODZINY = GODZINKI.NEXTVAL;
DROP SEQUENCE GODZINKI;
ALTER TABLE PRZYDZIALY ADD (CHECK(GODZINY <= 9999)) MODIFY (GODZINY NOT NULL);
SELECT * FROM PRZYDZIALY;

--7
ALTER TABLE PROJEKTY DISABLE CONSTRAINT UK_PROJEKTY;
SELECT CONSTRAINT_NAME, STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'UK_PROJEKTY';

--8
INSERT INTO PROJEKTY (OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA,FUNDUSZE) VALUES('INDEKSY_BITMAPOWE', TO_DATE('12-04-2015', 'DD-MM-YYYY'),TO_DATE('30-12-2016','DD-MM-YYYY'),40000);
