--1
CREATE VIEW ASYSTENCI (NAZWISKO, PLACA, STAZ) AS SELECT NAZWISKO, PLACA_POD, CURRENT_DATE- ZATRUDNIONY FROM PRACOWNICY WHERE ETAT = 'ASYSTENT';

--2
CREATE VIEW PLACE (ID_ZESP, SREDNIA, MINIMUM, MAX, FUNDUSZ, L_PENSJI, L_DOD) AS SELECT Z.ID_ZESP, AVG(P.PLACA_POD + COALESCE(P.PLACA_DOD, 0)) AS SREDNIA, MIN(P.PLACA_POD + COALESCE(P.PLACA_DOD, 0)) AS MINI, MAX(P.PLACA_POD + COALESCE(P.PLACA_DOD, 0)) AS MAX, SUM(P.PLACA_POD + COALESCE(P.PLACA_DOD, 0)) AS FUNDUSZ,  COUNT(*) AS L_PENSJI, SUM(P.PLACA_POD + COALESCE(P.PLACA_DOD, 0)) AS L_DOD FROM ZESPOLY Z JOIN PRACOWNICY P ON Z.ID_ZESP = P.ID_ZESP GROUP BY Z.ID_ZESP;

--3
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY P WHERE PLACA_POD < (SELECT SREDNIA FROM PLACE PP WHERE P.ID_ZESP = PP.ID_ZESP) ORDER BY PLACA_POD;

--4
CREATE VIEW PLACE_MINIMALNE (ID_PRAC, NAZWISKO, ETAT, PLACA_POD) AS SELECT ID_PRAC, NAZWISKO, ETAT, PLACA_POD FROM PRACOWNICY WHERE PLACA_POD <700 WITH READ ONLY;

--5
UPDATE PLACE_MINIMALNE SET PLACA_POD = 800 WHERE NAZWISKO = 'HAPKE';

--6
CREATE OR REPLACE VIEW PRAC_SZEF (ID_PRAC, ID_SZEFA, PRACOWNIK, ETAT, SZEF) AS SELECT P.ID_PRAC, P.ID_SZEFA, P.NAZWISKO, P.ETAT, S.NAZWISKO FROM PRACOWNICY P JOIN PRACOWNICY S ON P.ID_SZEFA = S.ID_PRAC;

--7
CREATE OR REPLACE VIEW ZAROBKI (ID_PRAC, NAZWISKO, ETAT, PLACA_POD) AS SELECT P.ID_PRAC, P.NAZWISKO, P.ETAT, P.PLACA_POD FROM PRACOWNICY P WHERE P.PLACA_POD < (SELECT PLACA_POD FROM PRACOWNICY S WHERE S.ID_PRAC = P.ID_SZEFA) WITH CHECK OPTION CONSTRAINT ZAROBKI;
--ORA-01402: view WITH CHECK OPTION where-clause violation
--Error at Line: 7 Column: 0

--8
SELECT * FROM USER_VIEWS;

--9
SELECT COLUMN_NAME, UPDATABLE, INSERTABLE, DELETABLE FROM USER_UPDATABLE_COLUMNS;

