--1
SELECT NAZWISKO, concat(SUBSTR(ETAT,0,2), ID_PRAC) AS KOD FROM PRACOWNICY;
--2
SELECT NAZWISKO, TRANSLATE(NAZWISKO,'KLM','XXX') AS WOJNA_LITEROM FROM PRACOWNICY;
--3
SELECT NAZWISKO FROM PRACOWNICY WHERE SUBSTR(NAZWISKO, 0, LENGTH(NAZWISKO)/2) LIKE '%L%';
--4
SELECT NAZWISKO, ROUND(PLACA_POD*1.15) AS PODWYZKA FROM PRACOWNICY;
--5
SELECT NAZWISKO, PLACA_POD, PLACA_POD*0.2 AS INWESTYCJA, (PLACA_POD*0.2)*(POWER(1.1,10)) AS KAPITAL, (PLACA_POD*0.2)*(POWER(1.1,10))-(PLACA_POD*0.2) AS ZYSK FROM PRACOWNICY;
--6
SELECT NAZWISKO, ZATRUDNIONY, FLOOR((TO_DATE('1/1/2000','DD/MM/YYYY')-ZATRUDNIONY)/365) AS STAZ FROM PRACOWNICY;
--7
SELECT NAZWISKO, TO_CHAR(ZATRUDNIONY, 'MONTH, dd yyyy') AS DATA_PRZYJECIA FROM PRACOWNICY WHERE ID_ZESP = 20;
--8
SELECT TO_CHAR(CURRENT_DATE, 'DAY') FROM DUAL;
--9
SELECT NAZWA, ADRES, CASE WHEN ADRES LIKE '%MIELZYNSKIEGO%' OR ADRES LIKE '%STRZELECKA%' THEN 'STARE MIASTO' WHEN ADRES LIKE '%PIOTROWO%' THEN 'NOWE MIASTO' WHEN ADRES LIKE'%WLODKOWICA%' THEN 'GRUNWALD' END AS DZIELNICA FROM ZESPOLY;
--10
SELECT NAZWISKO, PLACA_POD, CASE WHEN PLACA_POD>480 THEN 'POWYZEJ 480' WHEN PLACA_POD=480 THEN 'DOKLADNIE 480' ELSE 'PONIZEJ 480' END AS PROG FROM PRACOWNICY ORDER BY PLACA_POD DESC;
--11
SELECT NAZWISKO, PLACA_POD, DECODE(SIGN(PLACA_POD - 480), 1, 'POWYZEJ 480', 0, 'DOKLADNIE 480', -1, 'PONIZEJ 480') AS PROG FROM PRACOWNICY ORDER BY PLACA_POD DESC;
