SELECT MIN(PLACA_POD) AS MINIMUM ,MAX(PLACA_POD) AS MAKSIMUM, MAX(PLACA_POD) -MIN(PLACA_POD) AS ROZNICA FROM PRACOWNICY;

SELECT ETAT, AVG(PLACA_POD) FROM PRACOWNICY GROUP BY ETAT;

SELECT COUNT(*) FROM PRACOWNICY WHERE ETAT='PROFESOR';

SELECT ID_ZESP, SUM(PLACA_POD+COALESCE(PLACA_DOD,0)) AS SUMARYCZNE_PLACE FROM PRACOWNICY GROUP BY ID_ZESP ORDER BY ID_ZESP ASC;

SELECT MAX(SUM(PLACA_POD+COALESCE(PLACA_DOD,0))) FROM PRACOWNICY GROUP BY ID_ZESP;

SELECT ID_SZEFA, MIN(PLACA_POD) AS MINIMALNA FROM PRACOWNICY WHERE ID_SZEFA IS NOT NULL GROUP BY ID_SZEFA ORDER BY MINIMALNA DESC, ID_SZEFA ASC;

SELECT ID_ZESP, COUNT(ID_ZESP) AS ILU_PRACUJE FROM PRACOWNICY GROUP BY ID_ZESP ORDER BY ILU_PRACUJE DESC;

SELECT ID_ZESP, COUNT(ID_ZESP) AS ILU_PRACUJE FROM PRACOWNICY GROUP BY ID_ZESP HAVING COUNT(ID_ZESP)>3 ORDER BY ILU_PRACUJE DESC;

SELECT ID_PRAC, COUNT(ID_PRAC) FROM PRACOWNICY GROUP BY ID_PRAC HAVING COUNT(ID_PRAC)>1;

SELECT ETAT, AVG(PLACA_POD), COUNT(ETAT) FROM PRACOWNICY WHERE ZATRUDNIONY < '1990-01-01' GROUP BY ETAT ORDER BY ETAT ASC;

SELECT ID_ZESP, ETAT, ROUND(AVG(PLACA_POD+COALESCE(PLACA_DOD,0))) AS SREDNIA, ROUND(MAX(PLACA_POD+COALESCE(PLACA_DOD,0))) AS MAKSYMALNA FROM PRACOWNICY WHERE ETAT IN ('PROFESOR','ASYSTENT') GROUP BY ID_ZESP,ETAT ORDER BY ID_ZESP

SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, COUNT(*) AS ILU FROM PRACOWNICY GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY) ORDER BY ROK;

SELECT LENGTH(NAZWISKO) AS LITERY ,COUNT(*) AS "W ILU NAZWISKACH" FROM PRACOWNICY GROUP BY LENGTH(NAZWISKO) ORDER BY LITERY;

SELECT COUNT(*) AS "ILE NAZWISK Z A" FROM PRACOWNICY WHERE NAZWISKO LIKE '%A%' OR NAZWISKO LIKE '%a%';

SELECT COUNT(CASE WHEN INSTR(NAZWISKO, 'A',1,1) > 0 THEN 1 ELSE NULL END) AS ILE_NAZWISK_Z_A, COUNT(CASE WHEN INSTR(NAZWISKO, 'E',1,1) > 0 THEN 1 ELSE NULL END) AS ILE_NAZWISK_Z_E FROM PRACOWNICY

SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA_PLAC, LISTAGG(NAZWISKO || ':' || PLACA_POD, ',') WITHIN GROUP (ORDER BY NAZWISKO) AS PRACOWNICY FROM PRACOWNICY GROUP BY ID_ZESP; 