1
SELECT P.NAZWISKO, P.ID_ZESP, Z.NAZWA FROM PRACOWNICY P RIGHT JOIN ZESPOLY Z ON P.ID_ZESP=Z.ID_ZESP ORDER BY P.NAZWISKO;
2
SELECT Z.NAZWA, Z.ID_ZESP, COALESCE(P.NAZWISKO,'brak pracownikow') FROM PRACOWNICY P RIGHT JOIN ZESPOLY Z ON P.ID_ZESP=Z.ID_ZESP ORDER BY Z.NAZWA, P.NAZWISKO;
3
SELECT COALESCE(Z.NAZWA,'brak zespolu'), COALESCE(P.NAZWISKO,'brak pracownikow') FROM PRACOWNICY P FULL JOIN ZESPOLY Z ON P.ID_ZESP=Z.ID_ZESP ORDER BY Z.NAZWA, P.NAZWISKO;
4
SELECT Z.NAZWA, COUNT(P.ID_ZESP) AS LICZBA, COALESCE(SUM(P.PLACA_POD),0) AS SUMA_PLAC FROM PRACOWNICY P RIGHT JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP GROUP BY Z.NAZWA ORDER BY Z.NAZWA;
5

6
SELECT P.NAZWISKO AS PRACOWNIK, P.ID_PRAC, PP.NAZWISKO AS SZEF, PP.ID_PRAC AS ID_SZEFA FROM PRACOWNICY P LEFT JOIN PRACOWNICY PP ON P.ID_SZEFA=PP.ID_PRAC ORDER BY P.NAZWISKO;
7
SELECT SZEF.NAZWISKO, COUNT(POD.ID_PRAC) FROM PRACOWNICY SZEF FULL JOIN PRACOWNICY POD ON POD.ID_SZEFA = SZEF.ID_PRAC GROUP BY SZEF.NAZWISKO ORDER BY SZEF.NAZWISKO;