1
SELECT P.NAZWISKO, P.ID_ZESP, Z.NAZWA FROM PRACOWNICY P RIGHT JOIN ZESPOLY Z ON P.ID_ZESP=Z.ID_ZESP ORDER BY P.NAZWISKO;
2
SELECT Z.NAZWA, Z.ID_ZESP, COALESCE(P.NAZWISKO,'brak pracownikow') FROM PRACOWNICY P RIGHT JOIN ZESPOLY Z ON P.ID_ZESP=Z.ID_ZESP ORDER BY Z.NAZWA, P.NAZWISKO;
3
SELECT COALESCE(Z.NAZWA,'brak zespolu'), COALESCE(P.NAZWISKO,'brak pracownikow') FROM PRACOWNICY P FULL JOIN ZESPOLY Z ON P.ID_ZESP=Z.ID_ZESP ORDER BY Z.NAZWA, P.NAZWISKO;
4
SELECT Z.NAZWA, COUNT(P.ID_ZESP) AS LICZBA, COALESCE(SUM(P.PLACA_POD),0) AS SUMA_PLAC FROM PRACOWNICY P RIGHT JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP GROUP BY Z.NAZWA ORDER BY Z.NAZWA;
5
SELECT Z.NAZWA FROM ZESPOLY Z LEFT JOIN PRACOWNICY P ON Z.ID_ZESP = P.ID_ZESP WHERE P.ID_ZESP IS NULL;
6
SELECT P.NAZWISKO AS PRACOWNIK, P.ID_PRAC, PP.NAZWISKO AS SZEF, PP.ID_PRAC AS ID_SZEFA FROM PRACOWNICY P LEFT JOIN PRACOWNICY PP ON P.ID_SZEFA=PP.ID_PRAC ORDER BY P.NAZWISKO;
7
SELECT SZEF.NAZWISKO, COUNT(POD.ID_PRAC) FROM PRACOWNICY SZEF FULL JOIN PRACOWNICY POD ON POD.ID_SZEFA = SZEF.ID_PRAC GROUP BY SZEF.NAZWISKO ORDER BY SZEF.NAZWISKO;
8
SELECT P.NAZWISKO, P.ETAT, P.PLACA_POD, Z.NAZWA, PP.NAZWISKO AS SZEF FROM PRACOWNICY P LEFT JOIN PRACOWNICY PP ON P.ID_SZEFA = PP.ID_PRAC INNER JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP ORDER BY P.NAZWISKO;
9
SELECT NAZWISKO, NAZWA FROM PRACOWNICY CROSS JOIN ZESPOLY ORDER BY NAZWISKO, NAZWA;
10
SELECT COUNT(*) FROM PRACOWNICY, ETATY, ZESPOLY;
11
SELECT ETAT FROM PRACOWNICY WHERE EXTRACT(YEAR FROM ZATRUDNIONY) = 1992 INTERSECT SELECT ETAT FROM PRACOWNICY WHERE EXTRACT(YEAR FROM ZATRUDNIONY) = 1993;
12
SELECT ID_ZESP FROM ZESPOLY EXCEPT SELECT ID_ZESP FROM PRACOWNICY;
13
SELECT Z.ID_ZESP, Z.NAZWA FROM ZESPOLY Z EXCEPT SELECT P.ID_ZESP, Z.NAZWA FROM PRACOWNICY P JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP;
14
SELECT NAZWISKO, PLACA_POD, REPLACE(PLACA_POD, PLACA_POD, 'Poniżej 480 złotych') FROM PRACOWNICY WHERE PLACA_POD <480 UNION SELECT NAZWISKO, PLACA_POD, REPLACE(PLACA_POD, PLACA_POD, 'Dokladnie 480 złotych') FROM PRACOWNICY WHERE PLACA_POD =480 UNION SELECT NAZWISKO, PLACA_POD, REPLACE(PLACA_POD, PLACA_POD, 'Powyżej 480 złotych') FROM PRACOWNICY WHERE PLACA_POD >480 ORDER BY PLACA_POD;