--1
SELECT NAZWISKO, ETAT, ID_ZESP FROM PRACOWNICY WHERE ID_ZESP= (SELECT ID_ZESP FROM PRACOWNICY WHERE PRACOWNICY.NAZWISKO = 'BRZEZINSKI') ORDER BY PRACOWNICY.NAZWISKO;
--2
SELECT P.NAZWISKO, P.ETAT, Z.NAZWA FROM PRACOWNICY P JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP WHERE P.ID_ZESP= (SELECT ID_ZESP FROM PRACOWNICY WHERE PRACOWNICY.NAZWISKO = 'BRZEZINSKI') ORDER BY P.NAZWISKO;
--3
SELECT NAZWISKO, ETAT, ZATRUDNIONY FROM PRACOWNICY WHERE ZATRUDNIONY = (SELECT MIN(ZATRUDNIONY) FROM PRACOWNICY WHERE ETAT = 'PROFESOR');
--4
SELECT NAZWISKO, ZATRUDNIONY, ID_ZESP FROM PRACOWNICY WHERE (ZATRUDNIONY, ID_ZESP) IN (SELECT MAX(ZATRUDNIONY), ID_ZESP FROM PRACOWNICY GROUP BY ID_ZESP) ORDER BY ZATRUDNIONY;
--5
SELECT * FROM ZESPOLY WHERE ID_ZESP NOT IN (SELECT ID_ZESP FROM PRACOWNICY WHERE ID_ZESP IS NOT NULL);
--6
SELECT NAZWISKO FROM PRACOWNICY WHERE ETAT ='PROFESOR' AND ID_PRAC NOT IN (SELECT ID_SZEFA FROM PRACOWNICY WHERE ETAT = 'STAZYSTA' AND ID_SZEFA IS NOT NULL);
--7
SELECT P.ID_ZESP, SUM(P.PLACA_POD) AS SUMA_PLAC FROM PRACOWNICY P INNER JOIN ZESPOŁY Z ON P.ID_ZESP = Z.ID_ZESP GROUP BY P.ID_ZESP HAVING SUM(P.PLACA_POD) = (SELECT MAX(SUM(P.PLACA_POD)) FROM PRACOWNICY P INNER JOIN ZESPOŁY Z ON P.ID_ZESP = Z.ID_ZESP GROUP BY P.ID_ZESP) ORDER BY SUMA_PLAC DESC;
--8
SELECT Z.NAZWA, SUM(P.PLACA_POD) AS SUMA_PLAC FROM PRACOWNICY P INNER JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP GROUP BY Z.ID_ZESP, Z.NAZWA HAVING SUM(P.PLACA_POD) = (SELECT MAX(SUM(P.PLACA_POD)) FROM PRACOWNICY P INNER JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP GROUP BY P.ID_ZESP)ORDER BY SUMA_PLAC DESC;
--9
SELECT Z.NAZWA, COUNT(*) FROM ZESPOLY Z INNER JOIN PRACOWNICY P ON P.ID_ZESP = Z.ID_ZESP GROUP BY Z.ID_ZESP, Z.NAZWA HAVING COUNT(*) > (SELECT COUNT(*) FROM PRACOWNICY P LEFT JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP WHERE Z.NAZWA = 'ADMINISTRACJA' GROUP BY P.ID_ZESP);
--10
SELECT ETAT FROM PRACOWNICY GROUP BY ETAT HAVING COUNT(ETAT) = (SELECT MAX(COUNT(ETAT)) FROM PRACOWNICY GROUP BY ETAT) ORDER BY ETAT;
--11
SELECT ETAT, LISTAGG(NAZWISKO, ',') WITHIN GROUP (ORDER BY NAZWISKO) FROM PRACOWNICY GROUP BY ETAT HAVING COUNT(ETAT) = (SELECT MAX(COUNT(ETAT)) FROM PRACOWNICY GROUP BY ETAT) ORDER BY ETAT;
--12
SELECT P.NAZWISKO, PP.NAZWISKO AS SZEF FROM PRACOWNICY P INNER JOIN PRACOWNICY PP ON P.ID_SZEFA=PP.ID_PRAC WHERE PP.PLACA_POD-P.PLACA_POD = (SELECT MIN(PP.PLACA_POD-P.PLACA_POD) FROM PRACOWNICY P INNER JOIN PRACOWNICY PP ON P.ID_SZEFA=PP.ID_PRAC );