--1
SELECT * FROM ZESPOLY WHERE ID_ZESP NOT IN (SELECT ID_ZESP FROM PRACOWNICY);
--2
SELECT NAZWISKO, PLACA_POD, ETAT FROM PRACOWNICY P WHERE PLACA_POD > (SELECT AVG(PLACA_POD) FROM PRACOWNICY  WHERE ETAT=P.ETAT GROUP BY ETAT) ORDER BY P.PLACA_POD DESC;
--3
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY P WHERE PLACA_POD > (SELECT 0.75*PLACA_POD FROM PRACOWNICY WHERE ID_PRAC= P.ID_SZEFA);
--4
SELECT NAZWISKO FROM PRACOWNICY P WHERE ETAT ='PROFESOR' AND NOT EXISTS (SELECT ID_SZEFA, ETAT FROM PRACOWNICY WHERE ETAT ='STAZYSTA' AND P.ID_PRAC = ID_SZEFA);
--5
SELECT Z.NAZWA, M.MAKS_SUMA_PLAC FROM (SELECT MAX(SUM(PLACA_POD)) AS MAKS_SUMA_PLAC FROM PRACOWNICY GROUP BY ID_ZESP) M JOIN (SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA_PLAC FROM PRACOWNICY GROUP BY ID_ZESP) S ON S.SUMA_PLAC = M.MAKS_SUMA_PLAC JOIN ZESPOLY Z ON Z.ID_ZESP = S.ID_ZESP;
--6

--7
SELECT NAZWISKO, PLACA_POD, PLACA_POD - (SELECT AVG(PLACA_POD) FROM PRACOWNICY WHERE ID_ZESP = P.ID_ZESP) AS S FROM PRACOWNICY P ORDER BY NAZWISKO;
--8
