--1
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY ORDER BY PLACA_POD DESC FETCH FIRST 3 ROWS ONLY;

--2
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY ORDER BY PLACA_POD DESC OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;

--3
WITH ROZNICA AS (SELECT PP.NAZWISKO, PP.PLACA_POD, PP.PLACA_POD - (SELECT AVG(P.PLACA_POD) FROM PRACOWNICY P WHERE P.ID_ZESP = PP.ID_ZESP) AS R FROM PRACOWNICY PP) SELECT * FROM ROZNICA WHERE R>0;

--4
WITH LATA AS (SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, COUNT(*) AS ILOSC FROM PRACOWNICY GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY)) SELECT * FROM LATA ORDER BY ILOSC DESC;

--5
WITH LATA AS (SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, COUNT(*) AS ILOSC FROM PRACOWNICY GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY)) SELECT * FROM LATA FETCH FIRST 1 ROWS ONLY;

--6
???

--7
