--1
INSERT INTO PRACOWNICY (ID_PRAC, NAZWISKO, ETAT, ID_SZEFA, ZATRUDNIONY, PLACA_POD, PLACA_DOD, ID_ZESP) VALUES
    (250, 'KOWALSKI', 'ASYSTENT', NULL, '2015-01-13', 1500, NULL, 10);

SELECT * FROM PRACOWNICY WHERE ID_PRAC IN (250);

--2
UPDATE PRACOWNICY P SET (P.PLACA_POD, P.PLACA_DOD) = (SELECT 1.1* PP.PLACA_POD, COALESCE(1.2 * PP.PLACA_DOD, 100) FROM PRACOWNICY PP WHERE PP.ID_PRAC = 250) WHERE P.ID_PRAC = 250);

--3
INSERT INTO ZESPOLY (ID_ZESP, NAZWA, ADRES) VALUES 
    (60, 'BAZY DANYCH', 'PIOTROWO 2');

--4
UPDATE PRACOWNICY SET (ID_ZESP) = (SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA = 'BAZY DANYCH') WHERE ID_PRAC = 250;

--5
UPDATE PRACOWNICY SET ID_SZEFA = (SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO = 'MORZY') WHERE ID_ZESP = (SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA = 'BAZY DANYCH');

--6
DELETE FROM ZESPOLY WHERE NAZWA = 'BAZY DANYCH';
--ORA-02292: integrity constraint (SBD155638.FK_ID_ZESP) violated - child record found

--7
DELETE FROM PRACOWNICY WHERE ID_ZESP = (SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA = 'BAZY DANYCH');

--8
SELECT PP.NAZWISKO, PP.PLACA_POD, 0.1*(SELECT AVG(P.PLACA_POD) FROM PRACOWNICY P WHERE P.ID_ZESP = PP.ID_ZESP GROUP BY P.ID_ZESP) AS PODWYZKA FROM PRACOWNICY PP ORDER BY PP.NAZWISKO;

--9
UPDATE PRACOWNICY PP SET PP.PLACA_POD = PP.PLACA_POD + 0.1*(SELECT AVG(P.PLACA_POD) FROM PRACOWNICY P WHERE P.ID_ZESP = PP.ID_ZESP GROUP BY P.ID_ZESP);

--10
SELECT * FROM PRACOWNICY WHERE PLACA_POD = (SELECT MIN(PLACA_POD) FROM PRACOWNICY);

--11
UPDATE PRACOWNICY P SET P.PLACA_POD = (SELECT AVG(Z.PLACA_POD) FROM PRACOWNICY Z) WHERE PLACA_POD = (SELECT MIN(PLACA_POD) FROM PRACOWNICY);

--12
UPDATE PRACOWNICY PP SET PP.PLACA_DOD = (SELECT AVG(COALESCE(R.PLACA_DOD,0)) FROM PRACOWNICY R WHERE R.ID_SZEFA = (SELECT S.ID_PRAC FROM PRACOWNICY S WHERE S.NAZWISKO = 'MORZY')) WHERE PP.ID_ZESP=20;

--13
UPDATE PRACOWNICY P SET PLACA_POD = 1.25*PLACA_POD WHERE ID_ZESP = (SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA = 'SYSTEMY ROZPROSZONE');

--14
DELETE FROM PRACOWNICY WHERE ID_SZEFA = (SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO = 'MORZY');

--15
SELECT * FROM PRACOWNICY;

--16
